// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAaxC4YOrzz8YAI40KgJ4pxKDnKJxbPHA',
    appId: '1:719204335654:android:22a564448a63b3c973e6e7',
    messagingSenderId: '719204335654',
    projectId: 'fooddelivery-fd9c7',
    storageBucket: 'fooddelivery-fd9c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMH53KXVQbY_A6O6ZeE1a8vofYpjfhqoQ',
    appId: '1:719204335654:ios:24a8b95eb4a0a13d73e6e7',
    messagingSenderId: '719204335654',
    projectId: 'fooddelivery-fd9c7',
    storageBucket: 'fooddelivery-fd9c7.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryH2d',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMqtCS1WHbcvl0Y_c2a8MSAfWnKWeMGnk',
    appId: '1:719204335654:web:35eb386308c419e273e6e7',
    messagingSenderId: '719204335654',
    projectId: 'fooddelivery-fd9c7',
    authDomain: 'fooddelivery-fd9c7.firebaseapp.com',
    storageBucket: 'fooddelivery-fd9c7.firebasestorage.app',
    measurementId: 'G-B3PE1CW0ZN',
  );

}